### ISSUE TITLE
Sanitization issues

### ISSUE THREAD

**Issue by gyrus** [manzoorwanijk/cmb2-select-plus#5]
Thanks for the plugin. Works well apart from an apparent problem with `Select_Plus_CMB2_Field->sanitize_select_plus()`

After a lot of debugging (the values from the field weren't being saved), I found two things:

1. The incoming `$meta_value` was an array (I've set my select plus to be 'multiple'). But the field isn't repeatable. This triggered the condition on line 60, resulting in the array passed to `sanitize_text_field()` returning an empty string - which in turn led to this empty string being returned as the field's 'sanitized' value.
2. Even if I patched this, when the succeeding `foreach` loop passed the value of each array element to `array_map()`, PHP throws an error because each value of the array is a string (not an array).

I can't see the reason for either of the above, and anyway my custom field wasn't working without them. For now I've patched this by completely commenting out all the code in `sanitize_select_plus()` apart from the return statement.

Let me know what you think - maybe I'm missing something?

**Comment by manzoorwanijk** [comment]
@gyrus thank you for reporting that. Can you please verify that #6 fixes the issue?

**Comment by gyrus** [comment]
@manzoorwanijk Thanks, this seems to work well with my code

**Comment by manzoorwanijk** [comment]
Thank you for the confirmation

**Comment by manzoorwanijk** [comment]
I have published a release.

**Comment by gyrus** [comment]
@manzoorwanijk Many thanks for the quick response!
